// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFdxFUWlHIekwQUYJOCI2cRB3XFUXJyeM',
    appId: '1:495641627347:web:6577f858f44e7568b12226',
    messagingSenderId: '495641627347',
    projectId: 'pingme-caaf6',
    authDomain: 'pingme-caaf6.firebaseapp.com',
    storageBucket: 'pingme-caaf6.firebasestorage.app',
    measurementId: 'G-K0WWH5GSDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClyo-R_YGWSLkrysB5GsFV0tu7vzm_yAs',
    appId: '1:495641627347:android:d79a38c56d3f1cd4b12226',
    messagingSenderId: '495641627347',
    projectId: 'pingme-caaf6',
    storageBucket: 'pingme-caaf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJHoA53GYO_BizSjfvRDyrfPpTBJe9-Mw',
    appId: '1:495641627347:ios:4b4a521dcf274602b12226',
    messagingSenderId: '495641627347',
    projectId: 'pingme-caaf6',
    storageBucket: 'pingme-caaf6.firebasestorage.app',
    iosBundleId: 'com.example.pingme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJHoA53GYO_BizSjfvRDyrfPpTBJe9-Mw',
    appId: '1:495641627347:ios:4b4a521dcf274602b12226',
    messagingSenderId: '495641627347',
    projectId: 'pingme-caaf6',
    storageBucket: 'pingme-caaf6.firebasestorage.app',
    iosBundleId: 'com.example.pingme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFdxFUWlHIekwQUYJOCI2cRB3XFUXJyeM',
    appId: '1:495641627347:web:56159dc96fd7ec64b12226',
    messagingSenderId: '495641627347',
    projectId: 'pingme-caaf6',
    authDomain: 'pingme-caaf6.firebaseapp.com',
    storageBucket: 'pingme-caaf6.firebasestorage.app',
    measurementId: 'G-P6ZLKQ6JEZ',
  );
}
